### ISSUE TITLE
Blocked "river of realtime"

### ISSUE THREAD

**Issue by dimofte** [hoodsy/3ree-auth-example#5]
At the moment the client updates don't work as described by the diagram in the readme. 
If I open 2 clients with the same user, one doesn't get updated when the other makes changes (e.g. adding dashboards, lists etc)

**Comment by hoodsy** [comment]
@dimofte I am able to replicate your issue, and the cause is the lack of changefeed + socket connection.

Basically, this project currently supports the Hello, World realtime example of:
- Registering a new user, creating an organization (changefeed + socket connection established).
- _In an incognito window_, registering a second user, creating a second organization.
- Adding the second user to the first organization, and refreshing the second user's browser window
- Creating dashboards that populate in realtime

**Disclaimer:** only dashboards update in realtime, as RethinkDB doesn't support changefeeds across tables yet, and I would prefer to keep the current DB structure and wait for this release.

Again, currently the changefeed + socket connection is only made when an organization is created, so if the server is restarted, that connection will be lost. It's pretty brittle, but let's call it delicate.

As this is a basic example, I am hoping to expand it to a more stable, robust state... any and all contributions are very much welcome.
